# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('openid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=32)),
                ('avatarUrl', models.URLField(max_length=256)),
                ('gender', models.CharField(default='unKnow', max_length=8)),
                ('DSA', models.BooleanField(default=False)),
                ('DM', models.BooleanField(default=False)),
                ('EH', models.BooleanField(default=False)),
                ('VR', models.BooleanField(default=False)),
                ('SD', models.BooleanField(default=False)),
                ('SS', models.BooleanField(default=False)),
            ],
        ),
    ]
