# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20180125_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatarUrl',
            field=models.URLField(max_length=256),
        ),
        migrations.AlterField(
            model_name='student',
            name='nickname',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='student',
            name='openid',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
