# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-28 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20180127_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
